# -*- coding: utf-8 -*-
"""Day 2 Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mm9PjCW0zsrKdIbvkHkOj8mJvIV7zoYO
"""

#Day-2 Assignment
import collections
s='Hello' 
print(collections.Counter(s))