# -*- coding: utf-8 -*-
"""Day 3 Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mm9PjCW0zsrKdIbvkHkOj8mJvIV7zoYO
"""

#Day-3 Assignment
import random
import string
id =''
characters_list = list(string.ascii_letters + string.digits)
for i in range(6):
  id +=random.choice(characters_list)
print(id)