# -*- coding: utf-8 -*-
"""Day 3 Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mm9PjCW0zsrKdIbvkHkOj8mJvIV7zoYO
"""

#Day-3 Assignment
def mod_div(fun):
  def inner(a, b):
    if a < b:
      a, b = b, a
    fun(a, b)   

  return inner

@mod_div
def div(a, b):
  print(a / b)

div(2, 4)